backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "illustrations"
    label: "Illustrations"
    folder: "src/content/illustrations"
    create: true
    extension: 'json'
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Gallery Order", name: "order", widget: "number" }
      - { label: "File", name: "file", widget: "hidden", default: slug }
      - { label: "Main Image", name: "imageUrl", widget: "image" }
      - label: "More Images" 
        name: "list" 
        widget: "list" 
        collapsed: "true"
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Image", name: "imageUrl", widget: "image" }
