backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "illustrations"
    label: "Illustrations"
    folder: "src/content/illustrations"
    create: true
    extension: 'json'
    sortable_fields: ['commit_date', 'title', 'order']
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Gallery Order", name: "order", widget: "number", required: false }
      - { label: "Main Image", name: "imageUrl", widget: "image" }
      - { label: "Thumbnail Only", name: "thumbnailOnly", widget: "boolean", default: true }
      - label: "More Images" 
        name: "list" 
        widget: "list" 
        collapsed: true
        fields: 
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - { label: "Image", name: "imageUrl", widget: "image" }
      - label: "Galleries" 
        name: "gallery" 
        widget: "list" 
        collapsed: true
        fields: 
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - label: "Images"
            name: "imageList"
            widget: "list"
            fields: 
              - { label "Image", name: "image", widget: "image" }
  
  - name: "character-concepts"
    label: "Character Concepts"
    folder: "src/content/character-concepts"
    create: true
    extension: 'json'
    sortable_fields: ['commit_date', 'title', 'order']
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Gallery Order", name: "order", widget: "number", required: false }
      - { label: "Main Image", name: "imageUrl", widget: "image" }
      - { label: "Thumbnail Only", name: "thumbnailOnly", widget: "boolean", default: true }
      - label: "More Images" 
        name: "list" 
        widget: "list" 
        collapsed: true
        fields: 
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - { label: "Image", name: "imageUrl", widget: "image" }
      - label: "Galleries" 
        name: "gallery" 
        widget: "list" 
        collapsed: true
        fields: 
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - label: "Images"
            name: "imageList"
            widget: "list"
            fields: 
              - { label "Image", name: "image", widget: "image" }

  - name: "graphic-design"
    label: "Graphic Design"
    folder: "src/content/graphic-design"
    create: true
    extension: 'json'
    sortable_fields: ['commit_date', 'title', 'order']
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Gallery Order", name: "order", widget: "number", required: false }
      - { label: "Main Image", name: "imageUrl", widget: "image" }
      - { label: "Thumbnail Only", name: "thumbnailOnly", widget: "boolean", default: true }
      - label: "More Images" 
        name: "list" 
        widget: "list" 
        collapsed: true
        fields: 
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - { label: "Image", name: "imageUrl", widget: "image" }
      - label: "Galleries" 
        name: "gallery" 
        widget: "list" 
        collapsed: true
        fields: 
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - label: "Images"
            name: "imageList"
            widget: "list"
            fields: 
              - { label "Image", name: "image", widget: "image" }

  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    extension: 'json'
    sortable_fields: ['commit_date', 'title', 'order']
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Gallery Order", name: "order", widget: "number", required: false }
      - { label: "Main Image", name: "imageUrl", widget: "image" }
      - { label: "Thumbnail Only", name: "thumbnailOnly", widget: "boolean", default: true }
      - label: "More Images" 
        name: "gallery" 
        widget: "list" 
        collapsed: true
        fields: 
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - { label: "Image", name: "imageUrl", widget: "image" }
      - label: "Galleries" 
        name: "list" 
        widget: "list" 
        collapsed: true
        fields: 
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - label: "Images"
            name: "imageList"
            widget: "list"
            fields: 
              - { label "Image", name: "image", widget: "image" }